-- ============================================================
--  Database bootstrap — runs automatically on first container start
--  (mounted at /docker-entrypoint-initdb.d/init.sql)
-- ============================================================

-- ── Base table ───────────────────────────────────────────────────────────────
-- 'id' is a UUID string generated by the application layer (uuid.New()).
-- ON CONFLICT DO NOTHING in the worker INSERT makes replay idempotent.
CREATE TABLE IF NOT EXISTS orders (
    id           TEXT        PRIMARY KEY,
    product_name TEXT        NOT NULL,
    amount       NUMERIC     NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Materialized view ────────────────────────────────────────────────────────
-- Aggregates daily revenue. Refreshed hourly by the cron worker.
-- CONCURRENTLY means reads are not blocked during refresh (requires a unique index).
CREATE MATERIALIZED VIEW IF NOT EXISTS daily_sales_mv AS
    SELECT
        created_at::DATE AS sale_date,
        SUM(amount)      AS total_revenue
    FROM orders
    GROUP BY sale_date
WITH NO DATA;  -- populated on first REFRESH, not at creation time

-- Required for REFRESH MATERIALIZED VIEW CONCURRENTLY.
CREATE UNIQUE INDEX IF NOT EXISTS daily_sales_mv_date_idx ON daily_sales_mv (sale_date);

-- ── Seed the view with an initial refresh ────────────────────────────────────
REFRESH MATERIALIZED VIEW daily_sales_mv;
